//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 05:41:49 PM EST 
//


package _2022.camt_030_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CaseForwardingNotification3Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CaseForwardingNotification3Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FTHI"/>
 *     &lt;enumeration value="CANC"/>
 *     &lt;enumeration value="MODI"/>
 *     &lt;enumeration value="DTAU"/>
 *     &lt;enumeration value="SAIN"/>
 *     &lt;enumeration value="MINE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CaseForwardingNotification3Code")
@XmlEnum
public enum CaseForwardingNotification3Code {

    FTHI,
    CANC,
    MODI,
    DTAU,
    SAIN,
    MINE;

    public String value() {
        return name();
    }

    public static CaseForwardingNotification3Code fromValue(String v) {
        return valueOf(v);
    }

}
