//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 05:41:49 PM EST 
//


package _2022.fxtr_030_001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClearingBrokerIdentification1 complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClearingBrokerIdentification1">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SdInd" type="{urn:iso:std:iso:20022:tech:xsd:fxtr.030.001.04}SideIndicator1Code"/>
 *         &lt;element name="ClrBrkrId" type="{urn:iso:std:iso:20022:tech:xsd:fxtr.030.001.04}Max35Text"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearingBrokerIdentification1", propOrder = {
    "sdInd",
    "clrBrkrId"
})
public class ClearingBrokerIdentification1 {

    @XmlElement(name = "SdInd", required = true)
    @XmlSchemaType(name = "string")
    protected SideIndicator1Code sdInd;
    @XmlElement(name = "ClrBrkrId", required = true)
    protected String clrBrkrId;

    /**
     * Gets the value of the sdInd property.
     * 
     * @return
     *     possible object is
     *     {@link SideIndicator1Code }
     *     
     */
    public SideIndicator1Code getSdInd() {
        return sdInd;
    }

    /**
     * Sets the value of the sdInd property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideIndicator1Code }
     *     
     */
    public void setSdInd(SideIndicator1Code value) {
        this.sdInd = value;
    }

    /**
     * Gets the value of the clrBrkrId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClrBrkrId() {
        return clrBrkrId;
    }

    /**
     * Sets the value of the clrBrkrId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClrBrkrId(String value) {
        this.clrBrkrId = value;
    }

}
