//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 05:41:49 PM EST 
//


package _2022.fxtr_030_001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the _2022.fxtr_030_001 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("urn:iso:std:iso:20022:tech:xsd:fxtr.030.001.04", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: _2022.fxtr_030_001
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link DateAndDateTimeChoice }
     * 
     */
    public DateAndDateTimeChoice createDateAndDateTimeChoice() {
        return new DateAndDateTimeChoice();
    }

    /**
     * Create an instance of {@link SupplementaryDataEnvelope1 }
     * 
     */
    public SupplementaryDataEnvelope1 createSupplementaryDataEnvelope1() {
        return new SupplementaryDataEnvelope1();
    }

    /**
     * Create an instance of {@link PartyIdentification44 }
     * 
     */
    public PartyIdentification44 createPartyIdentification44() {
        return new PartyIdentification44();
    }

    /**
     * Create an instance of {@link Pagination }
     * 
     */
    public Pagination createPagination() {
        return new Pagination();
    }

    /**
     * Create an instance of {@link RegulatoryReporting4 }
     * 
     */
    public RegulatoryReporting4 createRegulatoryReporting4() {
        return new RegulatoryReporting4();
    }

    /**
     * Create an instance of {@link ClearingBrokerIdentification1 }
     * 
     */
    public ClearingBrokerIdentification1 createClearingBrokerIdentification1() {
        return new ClearingBrokerIdentification1();
    }

    /**
     * Create an instance of {@link TradeData11 }
     * 
     */
    public TradeData11 createTradeData11() {
        return new TradeData11();
    }

    /**
     * Create an instance of {@link TradeData12 }
     * 
     */
    public TradeData12 createTradeData12() {
        return new TradeData12();
    }

    /**
     * Create an instance of {@link PartyIdentification59 }
     * 
     */
    public PartyIdentification59 createPartyIdentification59() {
        return new PartyIdentification59();
    }

    /**
     * Create an instance of {@link TradingSideTransactionReporting1 }
     * 
     */
    public TradingSideTransactionReporting1 createTradingSideTransactionReporting1() {
        return new TradingSideTransactionReporting1();
    }

    /**
     * Create an instance of {@link ClearingSystemIdentification2Choice }
     * 
     */
    public ClearingSystemIdentification2Choice createClearingSystemIdentification2Choice() {
        return new ClearingSystemIdentification2Choice();
    }

    /**
     * Create an instance of {@link SupplementaryData1 }
     * 
     */
    public SupplementaryData1 createSupplementaryData1() {
        return new SupplementaryData1();
    }

    /**
     * Create an instance of {@link Status28Choice }
     * 
     */
    public Status28Choice createStatus28Choice() {
        return new Status28Choice();
    }

    /**
     * Create an instance of {@link PostalAddress1 }
     * 
     */
    public PostalAddress1 createPostalAddress1() {
        return new PostalAddress1();
    }

    /**
     * Create an instance of {@link NameAndAddress8 }
     * 
     */
    public NameAndAddress8 createNameAndAddress8() {
        return new NameAndAddress8();
    }

    /**
     * Create an instance of {@link PartyIdentification73Choice }
     * 
     */
    public PartyIdentification73Choice createPartyIdentification73Choice() {
        return new PartyIdentification73Choice();
    }

    /**
     * Create an instance of {@link ForeignExchangeTradeBulkStatusNotificationV04 }
     * 
     */
    public ForeignExchangeTradeBulkStatusNotificationV04 createForeignExchangeTradeBulkStatusNotificationV04() {
        return new ForeignExchangeTradeBulkStatusNotificationV04();
    }

    /**
     * Create an instance of {@link Status27Choice }
     * 
     */
    public Status27Choice createStatus27Choice() {
        return new Status27Choice();
    }

    /**
     * Create an instance of {@link StatusAndSubStatus2 }
     * 
     */
    public StatusAndSubStatus2 createStatusAndSubStatus2() {
        return new StatusAndSubStatus2();
    }

    /**
     * Create an instance of {@link UniqueTransactionIdentifier2 }
     * 
     */
    public UniqueTransactionIdentifier2 createUniqueTransactionIdentifier2() {
        return new UniqueTransactionIdentifier2();
    }

    /**
     * Create an instance of {@link CounterpartySideTransactionReporting1 }
     * 
     */
    public CounterpartySideTransactionReporting1 createCounterpartySideTransactionReporting1() {
        return new CounterpartySideTransactionReporting1();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:iso:std:iso:20022:tech:xsd:fxtr.030.001.04", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
