//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.02.03 at 05:41:49 PM EST 
//


package _2022.fxtr_030_001;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnderlyingProductIdentifier1Code.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UnderlyingProductIdentifier1Code">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FORW"/>
 *     &lt;enumeration value="NDFO"/>
 *     &lt;enumeration value="SPOT"/>
 *     &lt;enumeration value="SWAP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UnderlyingProductIdentifier1Code")
@XmlEnum
public enum UnderlyingProductIdentifier1Code {

    FORW,
    NDFO,
    SPOT,
    SWAP;

    public String value() {
        return name();
    }

    public static UnderlyingProductIdentifier1Code fromValue(String v) {
        return valueOf(v);
    }

}
